- build.gradle
- src/main/java/com/courseApp/DAO/CourseDAO.java
- src/main/java/com/courseApp/DAO/UserDAO.java
- src/main/java/com/courseApp/calendarService/CalendarFactory.java
- src/main/java/com/courseApp/calendarService/CalendarPresenter.java
- src/main/java/com/courseApp/calendarService/Presentable.java
- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/constants/Exceptions.java
- src/main/java/com/courseApp/courseService/CourseServiceController.java
- src/main/java/com/courseApp/driver/cmdline/CmdShell.java
- src/main/java/com/courseApp/driver/cmdline/ShellState.java
- src/main/java/com/courseApp/entity/Course.java
- src/main/java/com/courseApp/entity/User.java
- src/main/java/com/courseApp/userService/CourseServiceController.java
1. Phase 0 docs added.
2. Gradle Framework added for dependency mgmt.
3. Project skeleton updated.
HAPPY THANKS GIVING!
> [Kuan Pang] Project Setup

- src/main/java/com/courseApp/calendarService/CalendarFactory.java
- src/main/java/com/courseApp/calendarService/CalendarPresenter.java
- src/main/java/com/courseApp/constants/Constants.java
- src/test/java/com/courseApp/calendarService/CalendarPresenterTest.java
`CalendarPresenter` refined with constants added into file.
> CalendarService refinement

- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/driver/cmdline/ShellState.java
- src/main/java/com/courseApp/driver/cmdline/commands/GetScheduleSummary.java
- src/main/java/com/courseApp/driver/cmdline/commands/PresentCalendar.java
> Phase0 coding finished.

- phase0/crcCards/driver.cmdlineBranch/commandsBranch/PlanCourse.txt
- src/main/java/com/courseApp/Main.java
- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/driver/cmdline/CmdShell.java
- src/main/java/com/courseApp/driver/cmdline/commands/PlanCourse.java
ToDo: Progress Report + Sample Case
> PlanCourse CMD added.

- build.gradle
- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/courseService/CourseInformationGenerator.java
- src/main/java/com/courseApp/courseService/CourseServiceController.java
- src/main/java/com/courseApp/courseService/UseCourseBasicInfo.java
- src/main/java/com/courseApp/courseService/UseSectionSpecificScheduleInfo.java
- src/main/java/com/courseApp/dao/CourseDAO.java
- src/main/java/com/courseApp/dao/CourseDaoImpl.java
- src/main/java/com/courseApp/entity/Course.java
- src/test/java/com/courseApp/courseService/CourseServiceControllerTest.java
This pull request fixes #36 .
`CourseService` branch updated, new features added:
- showing instructor information in the summary
- querying instructor information with `CourseInformationGenerator`.
Note that tests are deleted.
Now `CourseService` is ready to integrate with `ReviewService` 👍
> [Kuan Pang] Course Service Update 

- src/main/java/com/courseApp/constants/Exceptions.java
- src/main/java/com/courseApp/reviewService/ControlRecommendationRank.java
- src/main/java/com/courseApp/reviewService/RecommendationRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewServiceController.java
- src/main/java/com/courseApp/reviewService/UseInferenceScore.java
- src/main/java/com/courseApp/reviewService/UseQueryRecommendationInfo.java
- src/main/java/com/courseApp/reviewService/UseRecommendationUpdate.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
- One more interface added to the `ReviewServiceController` (enables ranking of the instructor). @fanger2791 
- One more interface added to the `ReviewServiceProcessor` (enables recommendation metrics map generation) @syou1707 
- Test is suppressed, reserved for feature.
- Fixed typo in Constants.
> [Kuan pang] `ReviewService` Skeleton updated

- build.gradle
- src/main/java/com/courseApp/calendarService/CalendarPresenter.java
- src/main/java/com/courseApp/calendarService/WorkdayCalendar.java
- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/courseService/ControlPresentInformation.java
- src/main/java/com/courseApp/courseService/ControlUserCoursePlanning.java
- src/main/java/com/courseApp/courseService/CoursePlanner.java
- src/main/java/com/courseApp/courseService/CourseServiceController.java
- src/main/java/com/courseApp/dao/CourseDaoImpl.java
- src/main/java/com/courseApp/entity/CourseReview.java
- src/main/java/com/courseApp/entity/Schedule.java
- src/main/java/com/courseApp/reviewService/RecommendationRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- This PR fixes #49
- `Gradle.Build` refactored.
- Syntactic sugar suppressed, "TODO" added, so please check the todo to refactor your code.
- Check the issue #49 to see detailed instruction on syncing the environment.
> [Kuan pang] SDK Downgrade

- src/main/java/com/courseApp/calendarService/CalendarFactory.java
- src/main/java/com/courseApp/calendarService/CalendarPresenter.java
- src/main/java/com/courseApp/calendarService/FridayCalendar.java
- src/main/java/com/courseApp/calendarService/MondayCalendar.java
- src/main/java/com/courseApp/calendarService/SingledayCalendar.java
- src/main/java/com/courseApp/calendarService/ThursdayCalendar.java
- src/main/java/com/courseApp/calendarService/TuesdayCalendar.java
- src/main/java/com/courseApp/calendarService/UsePresentable.java
- src/main/java/com/courseApp/calendarService/WednesdayCalendar.java
- src/main/java/com/courseApp/calendarService/WeekCalendar.java
- src/main/java/com/courseApp/calendarService/WorkdayCalendar.java
- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/constants/Exceptions.java
- teamDocumentation/CalendarServiceDocumentation.md
Upgraded `CalendarFactory` with 2 new kinds(6 new types) of calendars to choose from. `CalendarPresenter` generates different calendars accordingly. Updated `CalendarService` documentation to illustrate the usage. Improved Jdoc and updated documentation. 
Constant name fixed, Throw statement added.
> Upgraded `CalendarService` with documentation

- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
ReviewRequestProcessor with new constants
> Recreate ReviewRequestProcessor

- phase1/progress_report.md
- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewServiceController.java
- src/main/java/com/courseApp/reviewService/UseQueryReview.java
- src/test/java/com/courseApp/dao/ReviewDaoImplTest.java
- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
- This pull request fixes #70
- Finished implementation `ReviewRequestProcessorTest`
- Bugs fixed in `ReviewRequestProcessor`, cause side effects in other classes of `ReviewService`. 
- Use of GitHub in `progress_report` and  `ReviewDaoImplTest`under construction.
> Finished `ReviewRequestProcessorTest`, bugs fixed in `ReviewRequestProcessor`

- src/main/java/com/courseApp/dao/ReviewDaoImpl.java
- src/main/java/com/courseApp/reviewService/ControlReviewCreation.java
- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewServiceController.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
- Finished implementation of`ReviewServiceControllerTest`- Bugs fixed in `ReviewRequestProcessor` and `ReviewServiceController` cause side effects in other classes of `ReviewService`.
> Finished `ReviewServiceControllerTest`, bugs fixed `ReviewServiceController`

- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
`ReviewServiceControllerTest` is now runnable.
> Bugs fixed `ReviewServiceControllerTest`

- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
> GitHub renewal

- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
Not testable testcases update in `ReviewServiceControllerTest`. Unused statement removed `ReviewRequestProcessorTest`
> Finalized test

- phase1/designdocument.assets/DDRefactoringCalendar
Added Calendar Refactoring in design documentation
> Added Calendar Refactoring documentation 

- phase1/designdocument.md
- This PR updated the progress summary in the Design Document.
- Hope its the last PR 🤓
> Progress summary updated - Fixed missing contribution part

- src/main/java/com/courseApp/calendarService/CalendarPresenter.java
- Removed unused parameter in `typeDecorator` method in `CalendarPresenter`.
> [Phase 1 Update]  Unused Param Fixed

- src/main/java/com/courseApp/driver/cmdline/commands/QuitSession.java
- src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewCourse.java
- src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewInst.java
- src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewUserReview.java
- src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/DeleteUserReview.java
- src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/EditUserReview.java
- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- src/main/java/com/courseApp/reviewService/ReviewServiceController.java
- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
- teamDocumentation/cmdDocumentation.md
- This PR fixes #90, the `getInstRank` is now running as expected.
- Several changes in the commands, users do not need to enter the username manually for executing `ReviewService`  cmds. E.g. `deleteUserReview` now deletes the user review under the current user.
- The CMD documentation is updated as well.
- Request validation is added to the `ReviewServiceProcessor`, improved accessibility for user. Detail instructions are added to the `CMDShell`.
- TODO, `getInstRank` test follow up @Lola-W. Might add more instructions to the `CMDShell`. 👍
> [Kuan Pang] Bug fixed and accessibility improvement 

- src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
- This PR fixes issue #92, the review Service and testcases are running properly.
- Fixed test cases in ReviewRequestProcessorTest, bug fixed in Review Service Controller
> Bug fixed and Test Case implemented

- src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
- src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
- Refined testcases in `ReviewService` by separation of static and dynamic users.
> Refined testcases in `ReviewService`.

- src/main/java/com/courseApp/constants/Constants.java
- src/main/java/com/courseApp/courseService/CoursePlanner.java
> minor change to checkconflict in planCourse

- src/main/resources/templates/calendar_service.html
- src/main/resources/templates/course_service.html
- src/main/resources/templates/introduction_dashboard.html
- src/main/resources/templates/login.html
- src/main/resources/templates/register.html
- src/main/resources/templates/result.html
- src/main/resources/templates/review_service.html
- src/main/resources/templates/schedule_service.html
Added Translation and high contrast toggle (the settings maintains while switching between pages so that's good!).
However, the high contrast color does not work with some elements of the page due to pre-set styling of these elements. I don't know how to fix this properly and don't want to mess up those elements.  SEND HELP
> Accessbility features

- README.md
- phase2/designdocument.md
- This PR fixes the link in `README` and `DesignDoc`
> [Phase 2 FINAL PR] Link fixed.
